import React from 'react';
import Link from 'next/link';

const Footer = () => {
  const generatorLinks = [
    { name: "Business Name", href: "/business-name-generator" },
    { name: "Username", href: "/username-generator" },
    { name: "Fantasy Name", href: "/fantasy-name-generator" },
    { name: "Random Name", href: "/random-name-generator" },
    { name: "Random Word", href: "/random-word-generator" },
    { name: "Book Title", href: "/book-title-generator" },
    { name: "Paragraph", href: "/paragraph-generator" },
    { name: "Slogan", href: "/slogan-generator" },
    { name: "Hashtag", href: "/hashtag-generator" },
    { name: "Company Name", href: "/company-name-generator" },
    { name: "Band Name", href: "/band-name-generator" },
    { name: "Character Name", href: "/character-name-generator" },
    { name: "Rap Lyrics", href: "/rap-lyrics-generator" },
    { name: "Random Password", href: "/random-password-generator" },
    { name: "Cover Letter", href: "/cover-letter-generator" },
    { name: "Brand Name", href: "/brand-name-generator" },
    { name: "Team Name", href: "/team-name-generator" },
    { name: "Nickname", href: "/nickname-generator" },
    { name: "Superhero Name", href: "/superhero-name-generator" },
    { name: "D&D Name", href: "/dnd-name-generator" },
    { name: "Poetry", href: "/poetry-generator" },
    { name: "Lyric", href: "/lyric-generator" },
    { name: "Rhyme", href: "/rhyme-generator" },
    { name: "Rapper Name", href: "/rapper-name-generator" },
    { name: "Fake Name", href: "/fake-name-generator" },
    { name: "Fake Email", href: "/fake-email-generator" },
    { name: "Random Letter", href: "/random-letter-generator" },
    { name: "Random Color", href: "/random-color-generator" },
    { name: "YouTube Title", href: "/youtube-title-generator" },
    { name: "Instagram Caption", href: "/instagram-caption-generator" },
    { name: "AI Content", href: "/ai-content-generator" },
    { name: "Bio", href: "/bio-generator" },
    { name: "Tweet", href: "/tweet-generator" },
    { name: "Meta Description", href: "/meta-description-generator" },
    { name: "Keyword", href: "/keyword-generator" },
    { name: "Facebook Post", href: "/facebook-post-generator" },
    { name: "TikTok Hashtag", href: "/tiktok-hashtag-generator" },
    { name: "Logo Name", href: "/logo-name-generator" },
    { name: "Domain Name", href: "/domain-name-generator" },
    { name: "Meme Text", href: "/meme-text-generator" },
    { name: "HTML Code", href: "/html-code-generator" },
    { name: "CSS Gradient", href: "/css-gradient-generator" },
    { name: "LinkedIn Headline", href: "/linkedin-headline-generator" },
    { name: "Shop Name", href: "/shop-name-generator" },
    { name: "Product Name", href: "/product-name-generator" },
    { name: "News Headline", href: "/news-headline-generator" },
    { name: "Script", href: "/script-generator" },
    { name: "YouTube Description", href: "/youtube-description-generator" },
    { name: "Instagram Bio", href: "/instagram-bio-generator" },
    { name: "Slogan Maker", href: "/slogan-maker" },
    { name: "Tagline", href: "/tagline-generator" },
    { name: "Mission Statement", href: "/mission-statement-generator" },
    { name: "Company Slogan", href: "/company-slogan-generator" },
    { name: "Store Name", href: "/store-name-generator" },
    { name: "Website Name", href: "/website-name-generator" },
    { name: "App Name", href: "/app-name-generator" },
    { name: "Game Name", href: "/game-name-generator" },
    { name: "Guild Name", href: "/guild-name-generator" },
    { name: "Clan Name", href: "/clan-name-generator" },
    { name: "Pet Name", href: "/pet-name-generator" },
    { name: "Cool Name", href: "/cool-name-generator" },
    { name: "Funny Name", href: "/funny-name-generator" },
    { name: "Sci Fi Name", href: "/sci-fi-name-generator" },
    { name: "Villain Name", href: "/villain-name-generator" },
    { name: "RPG Name", href: "/rpg-name-generator" },
    { name: "Anime Name", href: "/anime-name-generator" },
    { name: "Story Title", href: "/story-title-generator" },
    { name: "Song Title", href: "/song-title-generator" },
    { name: "DJ Name", href: "/dj-name-generator" },
    { name: "Artist Name", href: "/artist-name-generator" },
    { name: "Stage Name", href: "/stage-name-generator" },
    { name: "Band Logo", href: "/band-logo-generator" },
    { name: "Album Name", href: "/album-name-generator" },
    { name: "Playlist Name", href: "/playlist-name-generator" },
    { name: "Movie Title", href: "/movie-title-generator" },
    { name: "Film Name", href: "/film-name-generator" },
    { name: "Character Backstory", href: "/character-backstory-generator" },
    { name: "Plot", href: "/plot-generator" },
    { name: "Story Idea", href: "/story-idea-generator" },
    { name: "Writing Prompt", href: "/writing-prompt-generator" },
    { name: "Meme Caption", href: "/meme-caption-generator" },
    { name: "Pun", href: "/pun-generator" },
    { name: "Roast", href: "/roast-generator" },
    { name: "Comeback", href: "/comeback-generator" },
    { name: "Secure Password", href: "/secure-password-generator" },
    { name: "Random Date", href: "/random-date-generator" },
    { name: "Random Time", href: "/random-time-generator" },
    { name: "Quote", href: "/quote-generator" },
    { name: "Inspirational Quote", href: "/inspirational-quote-generator" },
    { name: "Motivational Quote", href: "/motivational-quote-generator" },
    { name: "Sports Team Name", href: "/sports-team-name-generator" },
    { name: "Fantasy Football Name", href: "/fantasy-football-name-generator" },
    { name: "Diet Plan", href: "/diet-plan-generator" },
    { name: "Meal Plan", href: "/meal-plan-generator" },
    { name: "Cocktail Name", href: "/cocktail-name-generator" },
    { name: "Restaurant Name", href: "/restaurant-name-generator" },
    { name: "Cafe Name", href: "/cafe-name-generator" },
    { name: "Twitch Username", href: "/twitch-username-generator" },
    { name: "Discord Name", href: "/discord-name-generator" },
    { name: "Xbox Gamertag", href: "/xbox-gamertag-generator" },
    { name: "Roblox Username", href: "/roblox-username-generator" },
    { name: "Fortnite Name", href: "/fortnite-name-generator" },
    { name: "Call of Duty Name", href: "/call-of-duty-name-generator" },
    { name: "PUBG Name", href: "/pubg-name-generator" },
    // New Lottery Generators Added
    { name: "Powerball", href: "/powerball-generator" },
    { name: "Mega Millions", href: "/mega-millions-generator" },
    { name: "Pick 5", href: "/pick-5-generator" },
    { name: "Fantasy 5", href: "/fantasy-5-generator" },
  ];

  return (
    <footer className="bg-gray-950 text-white py-12 px-4 md:px-8 lg:px-12 border-t border-blue-800">
      <div className="container mx-auto">
        <h3 className="text-3xl font-bold text-center mb-8 text-blue-400">Quick Links to Generators</h3>
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4 text-center">
          {generatorLinks.map((gen, index) => (
            <Link key={`footer-gen-${index}`} href={gen.href} className="text-gray-400 hover:text-blue-300 text-sm transition-colors py-1">
              {gen.name} Generator
            </Link>
          ))}
        </div>
      </div>
    </footer>
  );
};

export default Footer;
